# Generated by Django 4.2 on 2025-07-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciprs', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='調理時間（分）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='message',
            field=models.TextField(blank=True, verbose_name='投稿者からの一言'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='コメント内容'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='詳細（使っている材料など）'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
