# Generated by Django 4.2 on 2025-07-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciprs', '0004_recipe_cooking_time_recipe_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='材料名')),
                ('quantity', models.CharField(max_length=100, verbose_name='量')),
                ('unit', models.CharField(choices=[('個', '個'), ('本', '本'), ('枚', '枚'), ('匹', '匹'), ('尾', '尾'), ('合', '合'), ('切れ', '切れ'), ('大さじ', '大さじ'), ('小さじ', '小さじ'), ('ml', 'ml'), ('cc', 'cc'), ('g', 'g'), ('kg', 'kg'), ('袋', '袋'), ('適量', '適量'), ('少々', '少々'), ('ひとつまみ', 'ひとつまみ')], max_length=20, verbose_name='単位')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='reciprs.recipe')),
            ],
        ),
    ]
