# Generated by Django 4.2 on 2025-07-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciprs', '0005_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
    ]
