# Generated by Django 4.2 on 2025-07-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciprs', '0006_remove_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
