# Generated by Django 4.2 on 2025-07-16 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciprs', '0007_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='手順番号')),
                ('description', models.TextField(verbose_name='説明')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='reciprs.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
