# Generated by Django 4.2 on 2025-07-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciprs', '0009_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('個', '個'), ('本', '本'), ('枚', '枚'), ('匹', '匹'), ('尾', '尾'), ('合', '合'), ('切れ', '切れ'), ('大さじ', '大さじ'), ('小さじ', '小さじ'), ('ml', 'ml'), ('cc', 'cc'), ('g', 'g'), ('kg', 'kg'), ('袋', '袋'), ('適量', '適量'), ('少々', '少々'), ('ひとつまみ', 'ひとつまみ'), ('1/2', '1/2'), ('1/3', '1/3'), ('1/4', '1/4')], max_length=20, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=30, verbose_name='調理時間（分）'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=30, upload_to='recipe_images/', verbose_name='画像'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='message',
            field=models.TextField(verbose_name='投稿者からの一言'),
        ),
    ]
